//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Instance_Release = new HashSet<Instance_Release>();
        }
    
        public int Id_Book { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Author { get; set; }
        public Nullable<int> Id_Publishing_House { get; set; }
        public Nullable<int> Id_Type { get; set; }
        public Nullable<int> Id_Genre { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Pages { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book_Type Book_Type { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publishing_Houses Publishing_Houses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instance_Release> Instance_Release { get; set; }
    }
}
